Microsoft Windows [versão 10.0.19045.6396]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\trabalho2>python agrawala.py PeerC
[ricart.PeerC] registrado no nameserver.
[ricart.PeerC] Coordenador None não encontrado ou inativo. Iniciando eleição.

Estado atual: RELEASED[ricart.PeerC] Iniciando eleição Bully...

[ricart.PeerC] Eu sou o novo coordenador!
Digite [p] para pedir o recurso ou [q] para sair: [ricart.PeerC] Peer ricart.PeerD inativo, não respondendo à requisição.
p
[ricart.PeerC] Peers atualizados: ['ricart.Name', 'ricart.PeerA', 'ricart.PeerB', 'ricart.PeerD']
[ricart.PeerC] Pedindo recurso...
[ricart.PeerC] Falha ao enviar heartbeat para ricart.Name: the calling thread is not the owner of this proxy, create a new proxy in this thread or transfer ownership.
[ricart.PeerC] Peer ricart.Name removido. Peers restantes: ['ricart.PeerA', 'ricart.PeerB', 'ricart.PeerD']
Exception in thread Thread-6 (send_heartbeats_periodically):
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\trabalho2\agrawala.py", line 313, in send_heartbeats_periodically
    process.send_heartbeat()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\trabalho2\agrawala.py", line 65, in send_heartbeat
    for peer_name, peer_proxy in self.active_peers.items():
                                 ~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: dictionary changed size during iteration
[ricart.PeerC] Peer ricart.PeerD não disponível ao enviar requisição (cannot connect to ('localhost', 60442): [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente). Removendo.
[ricart.PeerC] Peer ricart.PeerD removido. Peers restantes: ['ricart.PeerA', 'ricart.PeerB']
Traceback (most recent call last):
  File "C:\trabalho2\agrawala.py", line 383, in <module>
    main()
    ~~~~^^
  File "C:\trabalho2\agrawala.py", line 380, in main
    interface(process)
    ~~~~~~~~~^^^^^^^^^
  File "C:\trabalho2\agrawala.py", line 335, in interface
    process.request_resource()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\trabalho2\agrawala.py", line 107, in request_resource
    for peer_name, peer_proxy in self.active_peers.items():
                                 ~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: dictionary changed size during iteration

C:\trabalho2>











































































